export const TOUCH_CONFIG = {
	TAP_MAX_DISTANCE: 18,
	TAP_MAX_DURATION: 280,
	MOVEMENT_THRESHOLD: 18,
} as const;

export const TOUCH_CONFIG_SQUARED = {
	TAP_DISTANCE_SQ: TOUCH_CONFIG.TAP_MAX_DISTANCE * TOUCH_CONFIG.TAP_MAX_DISTANCE,
	MOVEMENT_THRESHOLD_SQ: TOUCH_CONFIG.MOVEMENT_THRESHOLD * TOUCH_CONFIG.MOVEMENT_THRESHOLD,
} as const;

export const SELECTION_DEFAULTS = {
	SELECTED_WIDTH_SCALE: 1.1,
	SELECTED_HEIGHT_SCALE: 1.1,
	BORDER_WIDTH: 2,
	BORDER_COLOR: '#000000',
	ANIMATION_DURATION: 200,
} as const;
